#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LiceoVirtual.Resource", IsApplication=true)]

namespace LiceoVirtual
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int animabtn = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int black = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int gray_light = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int main_color_gray = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int main_color_gray_dk = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int main_color_gray_lt = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int main_color_green = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int transparent = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int white_smoke = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080001
			public const int pad_10dp = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int pad_15dp = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int pad_20dp = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int pad_30dp = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int pad_5dp = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int pad_chat_item = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int pad_chat_item1 = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int txt_12sp = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int txt_13sp = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int txt_14sp = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int txt_15sp = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int txt_16sp = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int txt_18sp = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int txt_20sp = 2131230734;
			
			// aapt resource value: 0x7f080007
			public const int txt_7sp = 2131230727;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int adn = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back_arrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int baseLogin = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int biology = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int candado = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int chat_bubble_gray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int chat_bubble_green = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int correct = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int editext_bg_gray = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int edittext_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int error = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int green_btn = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_overflow = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_compose = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_launcher = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_offline = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_online = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_pwd = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_send = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_username = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int incorrect = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int jugar = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int login_ic = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int LogoBlanco = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int logoLogin = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int LVBackground = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int LVBackgroundMenu = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int LVBlockedButton = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int LVButton = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int LVMenuBtn = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int LVProgress = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int n1_1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int n1_10 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int n1_11 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int n1_14 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int n1_15 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int n1_16 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int n1_17 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int n1_19 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int n1_2 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int n1_20 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int n1_21 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int n1_22 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int n1_25 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int n1_3 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int n1_4 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int n1_5 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int n1_6 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int n1_7 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int n1_8 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int n1_9 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int nota = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int punto = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int puntos = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int splash = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int student = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int student_sad = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int user_chat1 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int user_chat2 = 2130837565;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0036
			public const int aprovadas = 2131361846;
			
			// aapt resource value: 0x7f0a0015
			public const int backmenu = 2131361813;
			
			// aapt resource value: 0x7f0a0024
			public const int barraAvance = 2131361828;
			
			// aapt resource value: 0x7f0a0030
			public const int botonSiguiente = 2131361840;
			
			// aapt resource value: 0x7f0a001d
			public const int btn1 = 2131361821;
			
			// aapt resource value: 0x7f0a0020
			public const int btn2 = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int btn3 = 2131361822;
			
			// aapt resource value: 0x7f0a0021
			public const int btn4 = 2131361825;
			
			// aapt resource value: 0x7f0a0013
			public const int btnAceptarTerminoTrivia = 2131361811;
			
			// aapt resource value: 0x7f0a0033
			public const int btnIrTrivia = 2131361843;
			
			// aapt resource value: 0x7f0a0016
			public const int btnJugar = 2131361814;
			
			// aapt resource value: 0x7f0a000b
			public const int btnLogin = 2131361803;
			
			// aapt resource value: 0x7f0a0031
			public const int btnPreguntaSiguiente = 2131361841;
			
			// aapt resource value: 0x7f0a0019
			public const int btnRanking = 2131361817;
			
			// aapt resource value: 0x7f0a0009
			public const int cbxRecordarContrasena = 2131361801;
			
			// aapt resource value: 0x7f0a0045
			public const int cerrarSesion = 2131361861;
			
			// aapt resource value: 0x7f0a0039
			public const int completadas = 2131361849;
			
			// aapt resource value: 0x7f0a003e
			public const int content_frame = 2131361854;
			
			// aapt resource value: 0x7f0a0038
			public const int desaprovadas = 2131361848;
			
			// aapt resource value: 0x7f0a0008
			public const int edtContrasena = 2131361800;
			
			// aapt resource value: 0x7f0a0006
			public const int edtRut = 2131361798;
			
			// aapt resource value: 0x7f0a001b
			public const int imageView1 = 2131361819;
			
			// aapt resource value: 0x7f0a0001
			public const int imgAlerta = 2131361793;
			
			// aapt resource value: 0x7f0a0004
			public const int imgLogo = 2131361796;
			
			// aapt resource value: 0x7f0a0012
			public const int imgMensajeResultadoStudent = 2131361810;
			
			// aapt resource value: 0x7f0a002a
			public const int imgPregunta = 2131361834;
			
			// aapt resource value: 0x7f0a0034
			public const int info_menu = 2131361844;
			
			// aapt resource value: 0x7f0a0003
			public const int linearLayout1 = 2131361795;
			
			// aapt resource value: 0x7f0a0041
			public const int linearLayout1Ranking = 2131361857;
			
			// aapt resource value: 0x7f0a0005
			public const int linearLayout2 = 2131361797;
			
			// aapt resource value: 0x7f0a001c
			public const int linearLayout3 = 2131361820;
			
			// aapt resource value: 0x7f0a001f
			public const int linearLayout4 = 2131361823;
			
			// aapt resource value: 0x7f0a0010
			public const int linearLayout5 = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int linearLayout6 = 2131361807;
			
			// aapt resource value: 0x7f0a0000
			public const int linearLayoutAlerta = 2131361792;
			
			// aapt resource value: 0x7f0a0035
			public const int listViewPuntuacion = 2131361845;
			
			// aapt resource value: 0x7f0a0040
			public const int listViewRanking = 2131361856;
			
			// aapt resource value: 0x7f0a0032
			public const int lyPuntuacion1 = 2131361842;
			
			// aapt resource value: 0x7f0a003f
			public const int lyRanking1 = 2131361855;
			
			// aapt resource value: 0x7f0a000a
			public const int main = 2131361802;
			
			// aapt resource value: 0x7f0a0044
			public const int menuBar = 2131361860;
			
			// aapt resource value: 0x7f0a000c
			public const int myButton = 2131361804;
			
			// aapt resource value: 0x7f0a0025
			public const int pbPregunta = 2131361829;
			
			// aapt resource value: 0x7f0a003b
			public const int porcentaje = 2131361851;
			
			// aapt resource value: 0x7f0a0028
			public const int pregunta = 2131361832;
			
			// aapt resource value: 0x7f0a002c
			public const int radioGroup1 = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int rbOp1 = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int rbOp2 = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int rbOp3 = 2131361839;
			
			// aapt resource value: 0x7f0a0018
			public const int relativeLayout1 = 2131361816;
			
			// aapt resource value: 0x7f0a0014
			public const int relativeLayout2 = 2131361812;
			
			// aapt resource value: 0x7f0a0007
			public const int requestFocus1 = 2131361799;
			
			// aapt resource value: 0x7f0a002b
			public const int respuesta = 2131361835;
			
			// aapt resource value: 0x7f0a0027
			public const int scrollView1 = 2131361831;
			
			// aapt resource value: 0x7f0a0017
			public const int space1 = 2131361815;
			
			// aapt resource value: 0x7f0a001a
			public const int textView1 = 2131361818;
			
			// aapt resource value: 0x7f0a0037
			public const int textView3 = 2131361847;
			
			// aapt resource value: 0x7f0a003a
			public const int textView4 = 2131361850;
			
			// aapt resource value: 0x7f0a0002
			public const int tvAlerta = 2131361794;
			
			// aapt resource value: 0x7f0a0022
			public const int tvCorrectas = 2131361826;
			
			// aapt resource value: 0x7f0a003c
			public const int tvFecha = 2131361852;
			
			// aapt resource value: 0x7f0a0023
			public const int tvIncorrectas = 2131361827;
			
			// aapt resource value: 0x7f0a0042
			public const int tvNombreRanking = 2131361858;
			
			// aapt resource value: 0x7f0a0029
			public const int tvPregunta = 2131361833;
			
			// aapt resource value: 0x7f0a0026
			public const int tvProgreso = 2131361830;
			
			// aapt resource value: 0x7f0a003d
			public const int tvPuntaje = 2131361853;
			
			// aapt resource value: 0x7f0a0011
			public const int tvPuntajeMensajeResultado = 2131361809;
			
			// aapt resource value: 0x7f0a0043
			public const int tvPuntajeRanking = 2131361859;
			
			// aapt resource value: 0x7f0a000e
			public const int tvTextoMensajeResultado = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int v1 = 2131361805;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlertaRespuestaIncorrecta = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MensajeResultado = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Nivel = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Pregunta = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Puntuacion = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PuntuacionFragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PuntuacionPersonalizado = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PuntuacionTabs = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Ranking = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RankingPersonalizado = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int actionbar_main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int app_title = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int log_in = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int nivel_1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int nivel_2 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int nivel_3 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int nivel_4 = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int niveles = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int password = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int preguntas_n1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int preguntas_n2 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int preguntas_n3 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int preguntas_n4 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ranking_estudiantes = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int rut = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int trivianivel_1 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int trivianivel_2 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int trivianivel_3 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int trivianivel_4 = 2131099659;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppBaseTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AppTheme = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int btn = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int btn_green_white_bg = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int btn_menu = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btn_white_large = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int editext_graybg = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int editext_white = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int edittext_msg = 2131165191;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
